-- Persisted invoice + the transactional outbox. Schema owned by Flyway (standards rule 1).

CREATE TABLE invoice (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year                INTEGER       NOT NULL,
    number              INTEGER       NOT NULL,
    formatted_number    VARCHAR(32)   NOT NULL,
    state               VARCHAR(32)   NOT NULL,
    issue_date          DATE          NOT NULL,
    supplier_vat        VARCHAR(32)   NOT NULL,
    supplier_name       VARCHAR(255)  NOT NULL,
    customer_vat        VARCHAR(32)   NOT NULL,
    customer_name       VARCHAR(255)  NOT NULL,
    codice_destinatario VARCHAR(7)    NOT NULL,
    total_amount        NUMERIC(14,2) NOT NULL,
    xml                 TEXT          NOT NULL,
    created_at          TIMESTAMP     NOT NULL,
    -- The legal invariant, enforced by the database: numbers are unique and gap-less per year.
    CONSTRAINT uq_invoice_year_number UNIQUE (year, number),
    CONSTRAINT uq_invoice_formatted UNIQUE (formatted_number)
);

-- Transactional outbox: an event row committed in the SAME transaction as the invoice, so an
-- invoice can never be created without its "dispatch to SDI" intent, and vice versa. A relay
-- publishes unpublished rows and stamps published_at.
CREATE TABLE outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    type           VARCHAR(64)  NOT NULL,
    payload        TEXT         NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    published_at   TIMESTAMP,
    attempts       INTEGER      NOT NULL DEFAULT 0
);

-- Partial index over just the not-yet-published rows the relay polls (kept small as the table grows).
CREATE INDEX idx_outbox_unpublished ON outbox_event (created_at) WHERE published_at IS NULL;
